[package]
org = "tharindu"
name = "ride_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true
#cloud = "docker"
[[tool.persist]]
id = "generate-db-client"
targetModule = "ride_service"
options.datastore = "postgresql"
options.testDatastore = "h2"
filePath = "persist/model.bal"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.6.0"

