[ride_service]
PORT = 8082
WEBSOCKET_PORT = 27770
pub_key = "./public.crt"

[ride_service.repository]
host = "localhost"
port = 5432
user = "ride_user"
password = "ride_pass"
database = "ride_service_db"

[ride_service.user_service_client.userServiceClient]
url = "http://user_service/"
timeout = 120.0

[ride_service.bike_service_client.bikeServiceClient]
url = "http://bike-service/"
timeout = 120.0

[ride_service.reward_service_client.rewardServiceClient]
url = "http://reward-service/"
timeout = 120.0

[ride_service.user_service_client.userCapabilityCacheConfig]
capacity = 1000
evictionFactor = 0.25
defaultMaxAge = 300.0
cleanupInterval = 600.0

[ride_service.event_handler]
SERVER_URL = "localhost:9094"
RIDE_NOTIF_EVENTS_TOPIC = "ride-events"
PAYMENT_EVENTS_TOPIC = "payment-events"	

[ride_service.event_handler.producerConfiguration]
clientId = "event-producer"
acks = "all"
retryCount = 3

