version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ride_service_postgres
    restart: always
    environment:
      POSTGRES_USER: ride_user
      POSTGRES_PASSWORD: ride_pass
      POSTGRES_DB: ride_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
